#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Complete Analysis - Everything Knowable About the Key
Shows all information about the key, device, and how they work together
"""

import sys
import os
import json
import tinytuya
import time
import hashlib
import re

# Fix Windows console encoding
if sys.platform == 'win32':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')


def analyze_what_we_know():
    """Show everything we know about the key and device"""
    print("=" * 70)
    print("📊 COMPLETE KEY & DEVICE ANALYSIS")
    print("=" * 70)
    
    # Device Information
    print("\n" + "=" * 70)
    print("🔌 DEVICE INFORMATION")
    print("=" * 70)
    
    device_info = {
        "Device ID": "YOUR_DEVICE_ID",
        "IP Address": "YOUR_DEVICE_IP",
        "Protocol Version": "3.5",
        "Brand": "Avant",
        "Type": "Smart Lamp (Tuya-based)",
        "Port": "6668 (TCP)",
        "Protocol": "Tuya Local Protocol"
    }
    
    for key, value in device_info.items():
        print(f"  {key:20}: {value}")
    
    # Key Information (what we know about it)
    print("\n" + "=" * 70)
    print("🔑 KEY INFORMATION (What We Know)")
    print("=" * 70)
    
    print("\nKey Characteristics:")
    print("  - Type: local_key (also called device_secret or localKey)")
    print("  - Purpose: Encrypts/decrypts local network communication")
    print("  - Format: Usually 16 hexadecimal characters")
    print("  - Example format: '0123456789abcdef' (16 hex chars)")
    print("  - Location: Generated by Tuya when device is added to app")
    print("  - Storage: Stored in Tuya Cloud and Tuya Smart app")
    
    print("\nKey Properties:")
    print("  - Required for: All local control commands (on/off, brightness, etc.)")
    print("  - Not required for: Device discovery, network scanning")
    print("  - Security: Used for AES encryption of commands")
    print("  - Uniqueness: Each device has a unique key")
    print("  - Persistence: Key doesn't change unless device is reset/re-added")
    
    print("\nKey Usage:")
    print("  - Without key: Can discover device, connect, but cannot control")
    print("  - With key: Full control (on/off, brightness, color, etc.)")
    print("  - Error without key: 'Check device key or version' (Error 914)")
    
    # Current Status
    print("\n" + "=" * 70)
    print("📋 CURRENT STATUS")
    print("=" * 70)
    
    print("\n✅ What We Have:")
    print("  - Device ID: YOUR_DEVICE_ID")
    print("  - IP Address: YOUR_DEVICE_IP")
    print("  - Protocol Version: 3.5")
    print("  - Network connectivity: Working")
    print("  - Device discovery: Working")
    print("  - Tuya Cloud API credentials: Have them")
    
    print("\n❌ What We're Missing:")
    print("  - local_key: NOT FOUND YET")
    print("  - This is preventing device control")
    
    # Where Key Can Be Found
    print("\n" + "=" * 70)
    print("🔍 WHERE TO FIND THE KEY")
    print("=" * 70)
    
    locations = [
        {
            "Location": "Tuya IoT Platform Web Interface",
            "Path": "https://iot.tuya.com/ → Your Project → Device Management → Device Details",
            "Field Name": "Local Key" or "Device Secret" or "local_key",
            "Access": "Web browser (no API needed)",
            "Reliability": "⭐⭐⭐⭐⭐ (Best method)"
        },
        {
            "Location": "Tuya Smart App Database (Android Root)",
            "Path": "/data/data/com.tuya.smart/ → database files",
            "Field Name": "localKey column in device table",
            "Access": "Root file explorer + SQLite viewer",
            "Reliability": "⭐⭐⭐⭐ (If you have root)"
        },
        {
            "Location": "Network Packet Capture",
            "Path": "Wireshark capture → Tuya protocol packets",
            "Field Name": "Encrypted in network traffic",
            "Access": "Wireshark + network analysis",
            "Reliability": "⭐⭐⭐ (Requires expertise)"
        },
        {
            "Location": "Tuya Cloud API",
            "Path": "API call to /v1.0/devices/{device_id}",
            "Field Name": "local_key in response",
            "Access": "API with proper permissions",
            "Reliability": "❌ (Blocked by permissions - Code 28841001)"
        }
    ]
    
    for i, loc in enumerate(locations, 1):
        print(f"\n{i}. {loc['Location']}")
        print(f"   Path: {loc['Path']}")
        print(f"   Field: {loc['Field Name']}")
        print(f"   Access: {loc['Access']}")
        print(f"   Reliability: {loc['Reliability']}")
    
    # Key Format Analysis
    print("\n" + "=" * 70)
    print("🔬 KEY FORMAT ANALYSIS")
    print("=" * 70)
    
    print("\nExpected Format:")
    print("  - Length: 16 characters (most common)")
    print("  - Characters: Hexadecimal (0-9, a-f)")
    print("  - Case: Usually lowercase, sometimes uppercase")
    print("  - Example: 'a1b2c3d4e5f6g7h8' (16 hex chars)")
    
    print("\nValidation:")
    print("  - Must be valid hex: Only 0-9, a-f, A-F")
    print("  - Must be correct length: Usually 16, sometimes 32")
    print("  - Must match device: Each device has unique key")
    
    # How Key Works
    print("\n" + "=" * 70)
    print("⚙️  HOW THE KEY WORKS")
    print("=" * 70)
    
    print("\nEncryption Process:")
    print("  1. Your command (e.g., 'turn off') is created")
    print("  2. Command is encrypted using AES-128-CBC with local_key")
    print("  3. Encrypted command sent to device via TCP (port 6668)")
    print("  4. Device decrypts using same local_key")
    print("  5. Device executes command")
    print("  6. Device encrypts response with same key")
    print("  7. Response sent back and decrypted by your code")
    
    print("\nWithout Key:")
    print("  - Commands cannot be encrypted properly")
    print("  - Device rejects encrypted commands")
    print("  - Error: 'Check device key or version' (914)")
    
    print("\nWith Key:")
    print("  - Commands encrypted correctly")
    print("  - Device accepts and executes commands")
    print("  - Full control available")
    
    # Test Current Setup
    print("\n" + "=" * 70)
    print("🧪 TESTING CURRENT SETUP")
    print("=" * 70)
    
    # Check if key exists in any file
    key_found = False
    key_value = None
    
    files_to_check = [
        "tinytuya.json",
        "devices.json", 
        "avant_key.txt",
        "avant_control.py",
        "avant_key_config.py"
    ]
    
    print("\nChecking files for key...")
    for filename in files_to_check:
        if os.path.exists(filename):
            try:
                with open(filename, "r", encoding="utf-8") as f:
                    content = f.read()
                
                # Look for key patterns
                if filename.endswith(".json"):
                    data = json.loads(content)
                    if isinstance(data, dict):
                        # Check various key locations
                        for key_field in ["key", "local_key", "localKey", "device_secret"]:
                            if key_field in data:
                                key_value = data[key_field]
                                if key_value and len(key_value) >= 8:
                                    key_found = True
                                    print(f"  ✅ Found in {filename}: {key_field}")
                                    break
                elif filename.endswith(".py"):
                    # Look for AVANT_KEY assignment
                    match = re.search(r'AVANT_KEY\s*=\s*["\']([^"\']+)["\']', content)
                    if match:
                        key_value = match.group(1)
                        if key_value != "YOUR_LOCAL_KEY_HERE" and len(key_value) >= 8:
                            key_found = True
                            print(f"  ✅ Found in {filename}")
                elif filename.endswith(".txt"):
                    key_value = content.strip()
                    if key_value and len(key_value) >= 8:
                        key_found = True
                        print(f"  ✅ Found in {filename}")
            except:
                pass
    
    if not key_found:
        print("  ❌ No key found in any files")
    else:
        print(f"\n  🎉 Key found: {key_value[:8]}... (showing first 8 chars)")
        print(f"  Full length: {len(key_value)} characters")
        
        # Test the key
        print(f"\n  Testing key with device...")
        try:
            d = tinytuya.Device("YOUR_DEVICE_ID", "YOUR_DEVICE_IP")
            d.set_version("3.5")
            d.set_key(key_value)
            
            status = d.status()
            if status.get("Error"):
                print(f"  ❌ Key test failed: {status.get('Error')}")
            else:
                print(f"  ✅ KEY WORKS! Status: {status}")
                print(f"  🎉 Your key is VALID and FUNCTIONAL!")
        except Exception as e:
            print(f"  ⚠️  Test error: {e}")
    
    # Network Scan
    print("\nScanning network for device info...")
    try:
        devices = tinytuya.deviceScan()
        if devices and "YOUR_DEVICE_IP" in devices:
            info = devices["YOUR_DEVICE_IP"]
            print(f"  ✅ Device found on network")
            print(f"     Version: {info.get('version', 'Unknown')}")
            print(f"     Device ID: {info.get('gwId', 'Unknown')}")
    except:
        print(f"  ⚠️  Network scan failed")
    
    # Summary
    print("\n" + "=" * 70)
    print("📝 SUMMARY & NEXT STEPS")
    print("=" * 70)
    
    if key_found:
        print("\n✅ You have a key! Test it with:")
        print("   python avant_control.py status")
    else:
        print("\n❌ Key not found. Get it from:")
        print("   1. Tuya IoT Platform: https://iot.tuya.com/")
        print("      → Device Management → Your Device → Local Key")
        print("   2. Or use network packet capture")
        print("   3. Or extract from Tuya Smart app (if rooted)")
    
    print("\nOnce you have the key:")
    print("  1. Update avant_control.py: AVANT_KEY = 'your_key'")
    print("  2. Test: python avant_control.py status")
    print("  3. Control: python avant_control.py off")
    print("=" * 70 + "\n")


if __name__ == "__main__":
    analyze_what_we_know()
